events {
    worker_connections 1024;
}

http {
    upstream go_servers {
        least_conn;
        server gocommerce:8000;
        server gocommerce:8001;
        server gocommerce:8002;
        server gocommerce:8003;
        server gocommerce:8004;
        server gocommerce:8005;
        server gocommerce:8006;
        server gocommerce:8007;
        server gocommerce:8008;
        server gocommerce:8009;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://go_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}